using lab.Domain.Entities.Cadastro.Referencias;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Globalization;

namespace lab.Infra.Data.Config.Referencias
{
    public class Ref4316Configuration : IEntityTypeConfiguration<Ref4316>
    {
        public void Configure(EntityTypeBuilder<Ref4316> builder)
        {
            builder.HasKey(r => r.Id);
            builder.Property(r => r.Codigo).HasMaxLength(30).IsRequired();
            builder.Property(r => r.Descricao).HasMaxLength(255).IsRequired();
            builder.Property(r => r.DataInicial).IsRequired();
            builder.Property(r => r.Ncm).IsRequired();
			builder.HasData(
				new Ref4316() { Id = 1, Codigo = "101", Descricao = "Vendas a pessoa jurídica preponderantemente exportadora", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 2, Codigo = "102", Descricao = "Vendas a fabricante de veículos e carros blindados de combate, (NCM 8710.00.00) para uso pelas forças armadas ou órgãos de segurança pública brasileiros", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 3, Codigo = "103", Descricao = "Aquisição no mercado interno ou a importação, de forma combinada ou não, de mercadoria para emprego ou consumo na industrialização de produto a ser exportado, por pessoa jurídica previamente habilitada pela Secretaria de Comércio Exterior, (Drawback Integrado)", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 4, Codigo = "104", Descricao = "aquisição no mercado interno ou à importação de mercadorias para emprego em reparo, criação, cultivo ou atividade extrativista de produto a ser exportado", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 5, Codigo = "105", Descricao = "Aquisição no mercado interno ou importações de empresas denominadas fabricantes-intermediários, para industrialização de produto intermediário a ser diretamente fornecido a empresas industriais-exportadoras, para emprego ou consumo na industrialização de produto final destinado à exportação (Drawback Intermediário)", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 6, Codigo = "201", Descricao = "Insumos de origem animal, utilizados na fabricação de produtos destinados à alimentação humana ou animal", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 7, Codigo = "202", Descricao = "Insumos de origem vegetal, utilizados na fabricação de produtos destinados à alimentação humana ou animal", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 8, Codigo = "203", Descricao = "Soja e seus derivados classificados nos Capítulos 12, 15 e 23, todos da TIPI", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = DateTime.ParseExact("09102013", "ddMMyyyy", CultureInfo.InvariantCulture), Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 9, Codigo = "204", Descricao = "Venda de cerealista que exerça cumulativamente as atividades de limpar, padronizar, armazenar e comercializar os produtos in natura de origem vegetal, classificados nos códigos 09.01, 10.01 a 10.08, (exceto os dos códigos 1006.20 e 1006.30, 12.01 e 18.01) da NCM", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 10, Codigo = "205", Descricao = "Venda a granel de leite in natura, efetuada por pessoa jurídica que exerça cumulativamente as atividades de transporte e resfriamento deste produto", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 11, Codigo = "206", Descricao = "Venda por PJ que exerça atividade agropecuária ou por cooperativa de produção agropecuária de produto in natura de origem vegetal destinado à elaboração de mercadorias classificadas no código 22.04, da NCM", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 12, Codigo = "207", Descricao = "Venda de animais vivos classificados na posição 01.02, à pessoa jurídica que produza mercadoria classificada nas posições 02.01, 02.02, 02.06.10.00, 02.06.20, 02.06.21, 02.06.29, 05.06.90.00, 05.10.00.10 e 15.02.00.1 da NCM", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = DateTime.ParseExact("07032013", "ddMMyyyy", CultureInfo.InvariantCulture), Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 13, Codigo = "207", Descricao = "Venda de animais vivos classificados na posição 01.02 e 01.04, à pessoa jurídica que produza mercadoria classificada nas posições 02.01, 02.02, 02.04, 02.06.10.00, 02.06.20, 02.06.21, 02.06.29, 05.06.90.00, 05.10.00.10 e 15.02.00.1 da NCM", DataInicial = DateTime.ParseExact("08032013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 14, Codigo = "208", Descricao = "Vendas de produtos classificados nas posições 02.01, 02.02, 0206.10.00, 0206.20, 0206.21, 0206.29, 0506.90.00, 0510.00.10 e 1502.00.1, quando efetuadas por pessoa jurídica que revenda tais produtos ou que industrialize bens e produtos classificados nas posições 01.02, 02.01 e 02.02 da NCM", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = DateTime.ParseExact("07032013", "ddMMyyyy", CultureInfo.InvariantCulture), Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 15, Codigo = "209", Descricao = "Receita bruta da venda, no mercado interno, de:Iinsumos de origem vegetal IIpreparações dos tipos utilizados na alimentação de animais vivos;IIIanimais vivos classificados nas posições 01.03 e 01.05 da NCM;IVprodutos classificados nos códigos 02.03, 0206.30.00, 0206.4, 02.07 e 0210.1 da NCM", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = DateTime.ParseExact("26062011", "ddMMyyyy", CultureInfo.InvariantCulture), Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 16, Codigo = "209", Descricao = "Receita bruta da venda, no mercado interno, de:Iinsumos de origem vegetal IIpreparações dos tipos utilizados na alimentação de animais vivos;IIIanimais vivos classificados nas posições 01.03 e 01.05 da NCM;IVprodutos classificados nos códigos 02.03, 0206.30.00, 0206.4, 02.07 e 0210.1 da NCM", DataInicial = DateTime.ParseExact("27062011", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = DateTime.ParseExact("07032013", "ddMMyyyy", CultureInfo.InvariantCulture), Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 17, Codigo = "209", Descricao = "Receita bruta da venda, no mercado interno, de:Iinsumos de origem vegetal IIpreparações dos tipos utilizados na alimentação de animais vivos;IIIanimais vivos classificados nas posições 01.03 e 01.05 da NCM", DataInicial = DateTime.ParseExact("08032013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 18, Codigo = "210", Descricao = "Receitas decorrentes da venda dos produtos classificados nos códigos 0901.1 e 0901.90.00 da TIPI, exceto na venda a consumidor final", DataInicial = DateTime.ParseExact("01012012", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = DateTime.ParseExact("08032013", "ddMMyyyy", CultureInfo.InvariantCulture), Ncm = "", NcmEx = "09011;09019000", ExIpi = "" },
				new Ref4316() { Id = 19, Codigo = "211", Descricao = "Receitas decorrentes da venda de matéria-prima in natura de origem vegetal, destinada à produção de biodiesel, quando efetuada por pessoa jurídica que exerça atividade agropecuária, de cooperativa de produção agropecuária ou de cerealista que exerça cumulativamente as atividades de limpar, padronizar, armazenar e comercializar a MP para biodiesel", DataInicial = DateTime.ParseExact("01082012", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 20, Codigo = "212", Descricao = "Receitas decorrentes da venda dos produtos classificados no código 0805.10.00 da TIPI, quando utilizados na industrialização dos produtos classificados no código 2009.1 da TIPI, e estes forem destinados à exportação", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 21, Codigo = "213", Descricao = "Soja classificada na posição 12.01 e dos produtos classificados nos códigos 1208.10.00 e 2304.00 da TIPI", DataInicial = DateTime.ParseExact("10102013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "1201;12081000;230400", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 22, Codigo = "301", Descricao = "REPES - Regime Especial de Tributação para a Plataforma de Exportação de Serviços de Tecnologia da Informação", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 23, Codigo = "302", Descricao = "RECAP - Regime Especial de Aquisição de Bens de Capital para Empresas Exportadoras.- Venda e/ou importação de máquinas, aparelhos, instrumentos e equipamentos, para incorporação em seu ativo imobilizado", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 24, Codigo = "303", Descricao = "REIDI - Regime Especial de Incentivos para o Desenvolvimento da Infra-Estrutura", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 25, Codigo = "304", Descricao = "REPENEC - Regime Especial de Incentivos para o Desenvolvimento de Infraestrutura da Indústria Petrolífera nas Regiões Norte, Nordeste e Centro-Oeste", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 26, Codigo = "305", Descricao = "REPORTO - Regime Tributário para Incentivo à Modernização e à Ampliação da Estrutura Portuária", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 27, Codigo = "306", Descricao = "RECOMPE - Regime Especial de Aquisição de Computadores para Uso Educacional", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 28, Codigo = "307", Descricao = "RETAERO - Regime Especial para a Indústria Aeronáutica Brasileira", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 29, Codigo = "308", Descricao = "RECOM - Regime Especial de Tributação para Construção, Ampliação, Reforma ou Modernização de Estádios de Futebol", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 30, Codigo = "309", Descricao = "ZFM  Zona Franca de Manaus", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 31, Codigo = "310", Descricao = "ZPE  Zonas de Processamento de Exportação.- Importações ou aquisições no mercado interno de bens e serviços por empresa autorizada a operar em ZPE", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 32, Codigo = "311", Descricao = "Vendas realizadas no mercado interno para a Fifa, para Subsidiária Fifa no Brasil ou para a Emissora Fonte da Fifa, de mercadorias destinadas a uso ou consumo exclusivo na organização e realização da Copa das Confederações Fifa 2013 e da Copa do Mundo Fifa 2014", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 33, Codigo = "312", Descricao = "RECOF -  Regime de Entreposto Industrial sob Controle Aduaneiro InformatizadoImportação, com ou sem cobertura cambial, e com suspensão do pagamento de tributos, sob controle aduaneiro informatizado, de mercadorias que, depois de submetidas a operação de industrialização, sejam destinadas a exportação", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 34, Codigo = "313", Descricao = "RECOM - Regime Aduaneiro Especial de Importação de Insumos Destinados a Industrialização por Encomenda de Produtos Classificados nas Posições 8701 A 8705 da NCM. Importação de insumos, sem cobertura cambial, destinados a industrialização por encomenda de produtos classificados nas posições 8701 a 8705 da NCM.", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 35, Codigo = "401", Descricao = "Receitas de Fretes e de transporte multimodal, contratadas por pessoa jurídica preponderantemente exportadora, para transporte no mercado interno de produtos com suspensão ou destinados a Exportação", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 36, Codigo = "402", Descricao = "Venda de cana-de-açúcar, classificada na posição 12.12 da Nomenclatura Comum do Mercosul  NCM, efetuada para pessoa jurídica produtora de álcool, inclusive para fins carburantes", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 37, Codigo = "403", Descricao = "Venda de óleo combustível, tipo bunker, MF - Marine Fuel, classificado no código 2710.19.22, óleo combustível, tipo bunker, MGO - Marine Gás Oil, classificado no código 2710.19.21 e óleo combustível, tipo bunker, ODM - Óleo Diesel Marítimo, classificado no código 2710.19.21, quando destinados à navegação de cabotagem e de apoio portuário e marítimo", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 38, Codigo = "404", Descricao = "Acetona classificada no código 2914.11.00 da Tabela de Incidência do Imposto sobre Produtos Industrializados  Tipi, destinada à produção de monoisopropilamina (Mipa) utilizada na elaboração de defensivos agropecuários classificados na posição 38.08 da Tipi", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 39, Codigo = "405", Descricao = "Desperdícios, resíduos ou aparas de plástico, de papel ou cartão, de vidro, de ferro ou aço, de cobre, de níquel, de alumínio, de chumbo, de zinco e de estanho, e demais desperdícios e resíduos metálicos do Capítulo 81 da Tipi", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "3915;4707;7001;7204;7404;7503;7602;7802;7902;8002;81019700;81029700;81033000;81042000;81043000;81053000;81060090;81073000;81083000;81093000;81102000;81110090;81121300;81122200;81125200;81129200;81130090", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 40, Codigo = "406", Descricao = "Venda de produtos à pessoa jurídica sediada no exterior, com contrato de entrega no território nacional, de insumos destinados à industrialização, por conta e ordem da encomendante sediada no exterior, de máquinas e veículos classificados nas posições 87.01 a 87.05 da TIPI", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 41, Codigo = "407", Descricao = "Vendas a empresa sediada no exterior, para entrega em território nacional, de material de embalagem a ser totalmente utilizados no acondicionamento de mercadoria destinada à exportação para o exterior", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 42, Codigo = "408", Descricao = "Venda de máquinas e equipamentos classificados na posição 84.39, utilizados na fabricação de papéis destinados à impressão de jornais ou de papéis, destinados à impressão de periódicos, quando os referidos bens forem adquiridos por pessoa jurídica industrial para incorporação ao seu ativo imobilizado", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 43, Codigo = "901", Descricao = "Doações em espécie recebidas por instituições financeiras públicas controladas pela União e destinadas a ações de prevenção, monitoramento e combate ao desmatamento, inclusive programas de remuneração por serviços ambientais, e de promoção da conservação e do uso sustentável dos biomas brasileiros(Decreto nº 6.565, de 15 de setembro de 2008)", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 44, Codigo = "999", Descricao = "Código genérico  Operações com Suspensão", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 45, Codigo = "314", Descricao = "RECINE - Regime Especial de Tributação para Desenvolvimento da Atividade de Exibição Cinematográfica", DataInicial = DateTime.ParseExact("26032012", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 46, Codigo = "315", Descricao = "PROUCA - Programa Um Computador por Aluno. REICOMP - Regime Especial de Incentivo a Computadores para Uso Educacional", DataInicial = DateTime.ParseExact("11062012", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = DateTime.ParseExact("31122015", "ddMMyyyy", CultureInfo.InvariantCulture), Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 47, Codigo = "316", Descricao = "REPNBL-Redes - Regime Especial de Tributação do Programa Nacional de Banda Larga para Implantação de Redes de Telecomunicações", DataInicial = DateTime.ParseExact("04042012", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = DateTime.ParseExact("31122016", "ddMMyyyy", CultureInfo.InvariantCulture), Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 48, Codigo = "317", Descricao = "RETID - Regime Especial Tributário para a Indústria de Defesa", DataInicial = DateTime.ParseExact("30092011", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 49, Codigo = "318", Descricao = "REIF - Regime Especial de Incentivo ao Desenvolvimento da Infraestrutura da Indústria de Fertilizantes", DataInicial = DateTime.ParseExact("21092012", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 50, Codigo = "902", Descricao = "Receita das vendas de mercadorias e a prestação de serviços ocorridas no mercado interno para as entidades promotoras dos eventos olímpicos, conforme relacionadas no § 2º do art. 4º, da Lei nº 12.780/2013, destinadas exclusivamente à organização ou à realização dos Eventos Olímpicos e do Rio 2016", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = DateTime.ParseExact("31122017", "ddMMyyyy", CultureInfo.InvariantCulture), Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 51, Codigo = "319", Descricao = "Vendas de mercadorias e a prestação de serviços ocorridas no mercado interno para as pessoas jurídicas mencionadas no § 2o do art. 4o da Lei nº 12.780/2013, destinadas exclusivamente à organização ou à realização dos Jogos Olímpicos de 2016 e dos Jogos Paraolímpicos de 2016", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = DateTime.ParseExact("31122017", "ddMMyyyy", CultureInfo.InvariantCulture), Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 52, Codigo = "320", Descricao = "REPETRO-Industrialização-Venda no mercado interno de MP, PI e ME para serem utilizados integralmente no processo de industrialização de produto final destinado às atividades de exploração, de desenvolvimento e de produção de petróleo, de gás natural e de outros hidrocarbonetos fluidos à PJ habilitada no Repetro-Industrialização", DataInicial = DateTime.ParseExact("19072019", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4316() { Id = 53, Codigo = "321", Descricao = "REPETRO-SPED-Venda dos prod. finais dest. às ativ. de exploração, de desenv. e de prod. de petróleo, de GN e de outros hidrocarbonetos fluidos previstas na Lei 9478 de 1997, Lei 12276, de 2010, e Lei 12351, de 2010, por fab. desses, benef. do Repetro-Industrialização, quando diretamente adquiridos por PJ habilitada no Repetro ou Repetro-Sped", DataInicial = DateTime.ParseExact("19072019", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" }
			);
		}
    }
}
