using lab.Domain.Entities.Cadastro.Referencias;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Globalization;

namespace lab.Infra.Data.Config.Referencias
{
    public class Ref4317Configuration : IEntityTypeConfiguration<Ref4317>
    {
        public void Configure(EntityTypeBuilder<Ref4317> builder)
        {
            builder.HasKey(r => r.Id);
            builder.Property(r => r.Codigo).HasMaxLength(30).IsRequired();
            builder.Property(r => r.Descricao).HasMaxLength(255).IsRequired();
            builder.Property(r => r.DataInicial).IsRequired();
            builder.Property(r => r.Ncm).IsRequired();
			builder.HasData(
				new Ref4317() { Id = 1, Codigo = "101", Descricao = "Papel imune a impostos de que trata o art. 150, inciso VI, alínea d, da Constituição da República, quando destinados à impressão de periódicos", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
				new Ref4317()
				{
					Id = 2,
					Codigo = "201",
					Descricao = "Venda de produção própria por PJ industrial estabelecida na ZFM, para:- PJ estabelecida na ZFM;- PJ fora da ZFM desde que esta apure as contribuições no regime da não cumulatividade", DataInicial =  DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
	
				new Ref4317() { Id = 3, Codigo = "202", Descricao = "Venda de produção própria, por PJ industrial estabelecida na ZFM, para PJ estabelecida fora da ZFM: - que apura o imposto de renda com base no lucro real e que tenha sua receita, total ou parcialmente, excluída do regime de incidência não-cumulativa", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 4, Codigo = "203", Descricao = "Venda de produção própria, por PJ industrial estabelecida na ZFM, para PJ estabelecida fora da ZFM: - que apure o importo de renda com base no lucro presumido- que seja optante do SIMPLES- órgãos da administração federal, estadual, distrital e municipal", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317()
					{
						Id = 5,
						Codigo = "204",
						Descricao = "Venda de produção própria por pessoa jurídica industrial estabelecida nas Áreas de Livre Comércio para:- PJ estabelecida nas respectivas ALCs;- PJ fora da respectiva ALC desde que esta apure as contribuições no regime da não cumulatividade", DataInicial =  DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
	
				new Ref4317()
				{
					Id = 6,
					Codigo = "205",
					Descricao = "Revenda por pessoa jurídica comercial estabelecida nas Áreas de Livre Comércio para:- PJ estabelecida nas respectivas ALCs;- PJ fora da respectiva ALC desde que esta apure as contribuições no regime da não cumulatividade", DataInicial =  DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
	
				new Ref4317() { Id = 7, Codigo = "206", Descricao = "Venda de produção própria por pessoa jurídica industrial estabelecida nas Áreas de Livre Comércio para PJ estabelecida fora das respectivas ALCs que apure o importo de renda com base no lucro real e que tenha sua receita, total ou parcialmente, excluída do regime de incidência não-cumulativa", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 8, Codigo = "207", Descricao = "Venda de produção própria por pessoa jurídica industrial estabelecida nas Áreas de Livre Comércio para PJ estabelecida fora das respectivas ALCs: - que apure o importo de renda com base no lucro presumido- que seja optante do SIMPLES- órgãos da administração federal, estadual, distrital e municipal", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 9, Codigo = "208", Descricao = "Revenda por pessoa jurídica comercial estabelecida nas Áreas de Livre Comércio para PJ estabelecida fora das respectivas ALCs que apure o importo de renda com base no lucro real e que tenha sua receita, total ou parcialmente, excluída do regime de incidência não-cumulativa", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 10, Codigo = "209", Descricao = "Revenda por pessoa jurídica comercial estabelecida nas Áreas de Livre Comércio para PJ estabelecida fora das respectivas ALCs: - que apure o importo de renda com base no lucro presumido- que seja optante do SIMPLES- órgãos da administração federal, estadual, distrital e municipal", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 11, Codigo = "251", Descricao = "Devolução de venda de produção própria de pessoa jurídica industrial estabelecida na ZFM ou nas Áreas de Livre Comércio, bem como de venda de pessoa jurídica comercial estabelecida nas Áreas de Livre Comércio, tributada na operação de venda às alíquotas de 0,65% para o PIS/Pasep e de 3% para a Cofins.", DataInicial = DateTime.ParseExact("01012011", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 12, Codigo = "252", Descricao = "Devolução de venda de produção própria de pessoa jurídica industrial estabelecida na ZFM ou nas Áreas de Livre Comércio, ou de venda de pessoa jurídica comercial estabelecida nas Áreas de Livre Comércio, tributada na operação de venda às alíquotas de 1,3% para o PIS/Pasep e de 6% para a Cofins.", DataInicial = DateTime.ParseExact("01012011", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 13, Codigo = "301", Descricao = "Receita bruta auferida pela pessoa jurídica executora da encomenda de produtos monofásicos", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 14, Codigo = "901", Descricao = "Subcontratação de transporte de cargas", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 15, Codigo = "999", Descricao = "Demais produtos e operações sujeitos a alíquotas diferenciadas", DataInicial = DateTime.ParseExact("01012009", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 16, Codigo = "902", Descricao = "Créditos decorrentes da aquisição (importação) pelos importadores e fabricantes, dos produtos de que trata o art. 58-A, da Lei nº 10.833/03 (bebidas frias), para revenda", DataInicial = DateTime.ParseExact("01012011", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = DateTime.ParseExact("01052015", "ddMMyyyy", CultureInfo.InvariantCulture), Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 17, Codigo = "253", Descricao = "Venda de tablets PC (conforme especificações do art. 28 da Lei nº 11.196/2005) classificados na subposição 8471.41 da Tipi produzidos por pessoa jurídica estabelecida na Zona Franca de Manaus, para:- Pessoa jurídica estabelecida na ZFM;- Pessoa jurídica fora da ZFM desde que esta apure as contribuições exclusivamente no regime da não cumulatividade", DataInicial = DateTime.ParseExact("13102011", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 18, Codigo = "254", Descricao = "Venda de tablets PC (cfe. especificações do art. 28 da L. 11.196/2005) classificados na subposição 8471.41 da Tipi produzidos por PJ estabelecida na ZFM, para: PJ estabelecida fora da ZFM, e que apure o imposto de renda com base no lucro real e que tenha sua receita, total ou parcialmente, excluída do regime de incidência não-cumulativa", DataInicial = DateTime.ParseExact("13102011", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 19, Codigo = "911", Descricao = "Crédito na aquisição de bebidas frias, tributadas de acordo com a Lei nº 13.097/2015, adquirida de pessoa jurídica optante do Simples Nacional", DataInicial = DateTime.ParseExact("01052015", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 20, Codigo = "913", Descricao = "Receita financeira, auferida pelas pessoas jurídicas sujeitas ao regime de apuração não-cumulativa do PIS/Pasep e da Cofins", DataInicial = DateTime.ParseExact("01072015", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 21, Codigo = "914", Descricao = "Créditos decorrentes importação dos produtos de que trata o art. 14, incisos I, II e III, da Lei nº 13097/15 (bebidas frias).Volume de embalagem até 500 ml", DataInicial = DateTime.ParseExact("01102015", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = DateTime.ParseExact("31122015", "ddMMyyyy", CultureInfo.InvariantCulture), Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 22, Codigo = "914", Descricao = "Créditos decorrentes importação dos produtos de que trata o art. 14, incisos I, II e III, da Lei nº 13097/15 (bebidas frias).Volume de embalagem até 500 ml", DataInicial = DateTime.ParseExact("01012016", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = DateTime.ParseExact("31122016", "ddMMyyyy", CultureInfo.InvariantCulture), Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 23, Codigo = "914", Descricao = "Créditos decorrentes importação dos produtos de que trata o art. 14, incisos I, II e III, da Lei nº 13097/15 (bebidas frias).Volume de embalagem até 500 ml", DataInicial = DateTime.ParseExact("01012017", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = DateTime.ParseExact("31122017", "ddMMyyyy", CultureInfo.InvariantCulture), Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 24, Codigo = "914", Descricao = "Créditos decorrentes importação dos produtos de que trata o art. 14, incisos I, II e III, da Lei nº 13097/15 (bebidas frias).Volume de embalagem até 500 ml", DataInicial = DateTime.ParseExact("01012018", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 25, Codigo = "915", Descricao = "Créditos decorrentes importação dos produtos de que trata o art. 14, incisos I, II e III, da Lei nº 13097/15 (bebidas frias).Volume de embalagem acima de 500 ml", DataInicial = DateTime.ParseExact("01102015", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = DateTime.ParseExact("31122015", "ddMMyyyy", CultureInfo.InvariantCulture), Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 26, Codigo = "915", Descricao = "Créditos decorrentes importação dos produtos de que trata o art. 14, incisos I, II e III, da Lei nº 13097/15 (bebidas frias).Volume de embalagem acima de 500 ml", DataInicial = DateTime.ParseExact("01012016", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = DateTime.ParseExact("31122017", "ddMMyyyy", CultureInfo.InvariantCulture), Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 27, Codigo = "915", Descricao = "Créditos decorrentes importação dos produtos de que trata o art. 14, incisos I, II e III, da Lei nº 13097/15 (bebidas frias).Volume de embalagem acima de 500 ml", DataInicial = DateTime.ParseExact("01012018", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 28, Codigo = "916", Descricao = "Créditos decorrentes importação dos produtos de que trata o art. 14, inciso IV, da Lei nº 13097/15 (bebidas frias).Volume de embalagem até 400 ml", DataInicial = DateTime.ParseExact("01102015", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = DateTime.ParseExact("31122015", "ddMMyyyy", CultureInfo.InvariantCulture), Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 29, Codigo = "916", Descricao = "Créditos decorrentes importação dos produtos de que trata o art. 14, inciso IV, da Lei nº 13097/15 (bebidas frias).Volume de embalagem até 400 ml", DataInicial = DateTime.ParseExact("01012016", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = DateTime.ParseExact("31122016", "ddMMyyyy", CultureInfo.InvariantCulture), Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 30, Codigo = "916", Descricao = "Créditos decorrentes importação dos produtos de que trata o art. 14, inciso IV, da Lei nº 13097/15 (bebidas frias).Volume de embalagem até 400 ml", DataInicial = DateTime.ParseExact("01012017", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = DateTime.ParseExact("31122017", "ddMMyyyy", CultureInfo.InvariantCulture), Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 31, Codigo = "916", Descricao = "Créditos decorrentes importação dos produtos de que trata o art. 14, inciso IV, da Lei nº 13097/15 (bebidas frias).Volume de embalagem até 400 ml", DataInicial = DateTime.ParseExact("01012018", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 32, Codigo = "917", Descricao = "Créditos decorrentes importação dos produtos de que trata o art. 14, inciso IV, da Lei nº 13097/15 (bebidas frias).Volume de embalagem acima de 400 ml", DataInicial = DateTime.ParseExact("01102015", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = DateTime.ParseExact("31122015", "ddMMyyyy", CultureInfo.InvariantCulture), Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 33, Codigo = "917", Descricao = "Créditos decorrentes importação dos produtos de que trata o art. 14, inciso IV, da Lei nº 13097/15 (bebidas frias).Volume de embalagem acima de 400 ml", DataInicial = DateTime.ParseExact("01012016", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = DateTime.ParseExact("31122017", "ddMMyyyy", CultureInfo.InvariantCulture), Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 34, Codigo = "917", Descricao = "Créditos decorrentes importação dos produtos de que trata o art. 14, inciso IV, da Lei nº 13097/15 (bebidas frias).Volume de embalagem acima de 400 ml", DataInicial = DateTime.ParseExact("01012018", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 35, Codigo = "903", Descricao = "Créditos originários da importação de bens em geral - Art. 8º e 15 da Lei nº 10.865/2004 (Alíquotas majoradas conforme MP nº 668/2015, convertida na Lei nº 13.137/2015)", DataInicial = DateTime.ParseExact("01052015", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 36, Codigo = "904", Descricao = "Créditos originários da importação de produtos farmacêuticos - Art. 8º, § 1º  e art. 17 da Lei nº 10.865/2004 (Alíquotas majoradas conforme MP nº 668/2015, convertida na Lei nº 13.137/2015)", DataInicial = DateTime.ParseExact("01052015", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 37, Codigo = "905", Descricao = "Créditos originários da importação de produtos de perfumaria, de toucador e de higiene pessoal - Art. 8º, § 2º e  art. 17 da Lei nº 10.865/2004 (Alíquotas majoradas conforme MP nº 668/2015, convertida na Lei nº 13.137/2015)", DataInicial = DateTime.ParseExact("01052015", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 38, Codigo = "906", Descricao = "Créditos originários da importação de máquinas e veículos - Art. 8º, § 3º e art. 17 da Lei nº 10.865/2004 (Alíquotas majoradas conforme MP nº 668/2015, convertida na Lei nº 13.137/2015)", DataInicial = DateTime.ParseExact("01052015", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 39, Codigo = "907", Descricao = "Créditos originários da importação de pneus novos e câmaras-de-ar, de borracha - Art. 8º, § 5º e art. 17 da Lei nº 10.865/2004 (Alíquotas majoradas conforme MP nº 668/2015)", DataInicial = DateTime.ParseExact("01052015", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = DateTime.ParseExact("21062015", "ddMMyyyy", CultureInfo.InvariantCulture), Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 40, Codigo = "907", Descricao = "Créditos originários da importação de pneus novos e câmaras-de-ar, de borracha - Art. 8º, § 5º e art. 17 da Lei nº 10.865/2004 (Alíquotas majoradas conforme Lei nº 13.137/2015)", DataInicial = DateTime.ParseExact("22062015", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 41, Codigo = "908", Descricao = "Créditos originários da importação de autopeças - Art. 8º, § 9º e art. 17 da Lei nº 10.865/2004 (Alíquotas majoradas conforme MP nº 668/2015)", DataInicial = DateTime.ParseExact("01052015", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = DateTime.ParseExact("31082015", "ddMMyyyy", CultureInfo.InvariantCulture), Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 42, Codigo = "908", Descricao = "Créditos originários da importação de autopeças - Art. 8º, § 9º e art. 17 da Lei nº 10.865/2004 (Alíquotas majoradas conforme Lei nº 13.137/2015)", DataInicial = DateTime.ParseExact("01092015", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 43, Codigo = "909", Descricao = "Créditos originários da importação de papel imune a impostos - Art. 8º, § 10 e art. 17 da Lei nº 10.865/2004 (Alíquotas majoradas conforme MP nº 668/2015)", DataInicial = DateTime.ParseExact("01052015", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = DateTime.ParseExact("21062015", "ddMMyyyy", CultureInfo.InvariantCulture), Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 44, Codigo = "909", Descricao = "Créditos originários da importação de papel imune a impostos - Art. 8º, § 10 e art. 17 da Lei nº 10.865/2004 (Alíquotas majoradas conforme Lei nº 13.137/2015)", DataInicial = DateTime.ParseExact("22062015", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 45, Codigo = "401", Descricao = "Créditos referentes a devoluções cuja receita auferida foi tributada com alíquota de 0,18% (PIS) e 0,82% (COFINS)", DataInicial = DateTime.ParseExact("01012016", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 46, Codigo = "402", Descricao = "Créditos referentes a devoluções cuja receita auferida foi tributada com alíquota de 1,19% (PIS) e 5,46% (COFINS)", DataInicial = DateTime.ParseExact("01012016", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 47, Codigo = "403", Descricao = "Créditos referentes a devoluções cuja receita auferida foi tributada com alíquota de 1,34% (PIS) e 6,15% (COFINS)", DataInicial = DateTime.ParseExact("01012016", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 48, Codigo = "404", Descricao = "Créditos referentes a devoluções cuja receita auferida foi tributada com alíquota de 1,49% (PIS) e 6,83% (COFINS)", DataInicial = DateTime.ParseExact("01012016", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 49, Codigo = "405", Descricao = "Créditos referentes a devoluções cuja receita auferida foi tributada com alíquota de 1,50% (PIS) e 6,92% (COFINS)", DataInicial = DateTime.ParseExact("01012016", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 50, Codigo = "406", Descricao = "Créditos referentes a devoluções cuja receita auferida foi tributada com alíquota de 1,67% (PIS) e 7,69% (COFINS)", DataInicial = DateTime.ParseExact("01012016", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 51, Codigo = "407", Descricao = "Créditos referentes a devoluções cuja receita auferida foi tributada com alíquota de 1,86% (PIS) e 8,54% (COFINS)", DataInicial = DateTime.ParseExact("01012016", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 52, Codigo = "408", Descricao = "Créditos referentes a devoluções cuja receita auferida foi tributada com alíquota de 1,88% (PIS) e 8,65% (COFINS)", DataInicial = DateTime.ParseExact("01012016", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 53, Codigo = "409", Descricao = "Créditos referentes a devoluções cuja receita auferida foi tributada com alíquota de 2,09% (PIS) e 9,61% (COFINS)", DataInicial = DateTime.ParseExact("01012016", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 54, Codigo = "410", Descricao = "Créditos referentes a devoluções cuja receita auferida foi tributada com alíquota de 0,54% (PIS) e 2,46% (COFINS)", DataInicial = DateTime.ParseExact("01012017", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 55, Codigo = "411", Descricao = "Créditos referentes a devoluções cuja receita auferida foi tributada com alíquota de 1,11% (PIS) e 5,02% (COFINS)", DataInicial = DateTime.ParseExact("09032016", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 56, Codigo = "412", Descricao = "Créditos referentes a devoluções cuja receita auferida foi tributada com alíquota de 1,26% (PIS) e 5,81% (COFINS)", DataInicial = DateTime.ParseExact("01012017", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 57, Codigo = "413", Descricao = "Créditos referentes a devoluções cuja receita auferida foi tributada com alíquota de 1,42% (PIS) e 6,53% (COFINS)", DataInicial = DateTime.ParseExact("01012017", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 58, Codigo = "414", Descricao = "Créditos referentes a devoluções cuja receita auferida foi tributada com alíquota de 1,58% (PIS) e 7,26% (COFINS)", DataInicial = DateTime.ParseExact("01012017", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 59, Codigo = "415", Descricao = "Créditos referentes a devoluções cuja receita auferida foi tributada com alíquota de 1,77% (PIS) e 8,11% (COFINS)", DataInicial = DateTime.ParseExact("01012017", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 60, Codigo = "416", Descricao = "Créditos referentes a devoluções cuja receita auferida foi tributada com alíquota de 1,97% (PIS) e 9,08% (COFINS)", DataInicial = DateTime.ParseExact("01012017", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 61, Codigo = "417", Descricao = "Créditos referentes a devoluções cuja receita auferida foi tributada com alíquota de 1,98% (PIS) e 9,13% (COFINS)", DataInicial = DateTime.ParseExact("01012018", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 62, Codigo = "418", Descricao = "Créditos referentes a devoluções cuja receita auferida foi tributada com alíquota de 2,20% (PIS) e 10,15% (COFINS)", DataInicial = DateTime.ParseExact("01012018", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" },
					new Ref4317() { Id = 63, Codigo = "419", Descricao = "Créditos referentes a devoluções cuja receita auferida foi tributada com alíquota de 1,59% (PIS) e 7,30% (COFINS)", DataInicial = DateTime.ParseExact("01012018", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, Ncm = "", NcmEx = "", ExIpi = "" }
			);
		}
    }
}
