using lab.Domain.Entities.Cadastro.Referencias;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Globalization;

namespace lab.Infra.Data.Config.Referencias
{
    public class Ref712Configuration : IEntityTypeConfiguration<Ref712>
    {
        public void Configure(EntityTypeBuilder<Ref712> builder)
        {
            builder.HasKey(r => r.Id);
            builder.Property(r => r.Codigo).HasMaxLength(30).IsRequired();
            builder.Property(r => r.Descricao).HasMaxLength(255).IsRequired();
            builder.Property(r => r.DataInicial).IsRequired();
			builder.HasData(
				new Ref712() { Id = 1, Codigo = "D0001", Descricao = "Reversões de provisões", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "01;02;03;04;05;06", IndAjuste = "P", Grupo = "000", IndOutros = "N", IndTipoDeducoes = "G" },
				new Ref712() { Id = 2, Codigo = "D0002", Descricao = "Recuperações de créditos baixados como perda, limitados aos valores efetivamente baixados, que não representem ingresso de novas receitas", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "01;02;03;04;05;06", IndAjuste = "P", Grupo = "000", IndOutros = "N", IndTipoDeducoes = "G" },
				new Ref712() { Id = 3, Codigo = "D0003", Descricao = "Resultado positivo da avaliação de investimentos pelo valor do patrimônio líquido", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "01;02;03;04;05;06", IndAjuste = "P", Grupo = "000", IndOutros = "N", IndTipoDeducoes = "G" },
				new Ref712() { Id = 4, Codigo = "D0004", Descricao = "Lucros e dividendos derivados de investimentos avaliados pelo custo de aquisição, que tenham sido computados como receita", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "01;02;03;04;05;06", IndAjuste = "P", Grupo = "000", IndOutros = "N", IndTipoDeducoes = "G" },
				new Ref712() { Id = 5, Codigo = "D0005", Descricao = "Receita decorrente da venda de bens do ativo permanente", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "01;02;03;04;05;06", IndAjuste = "P", Grupo = "000", IndOutros = "N", IndTipoDeducoes = "G" },
				new Ref712() { Id = 6, Codigo = "D0006", Descricao = "Vendas canceladas, os descontos incondicionais concedidos, e o IPI e ICMS quando cobrado pelo vendedor dos bens ou prestador dos serviços na condição de substituto tributário", DataInicial = DateTime.ParseExact("01012014", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "01;02;03;04;05;06", IndAjuste = "P", Grupo = "000", IndOutros = "N", IndTipoDeducoes = "G" },
				new Ref712() { Id = 7, Codigo = "D0090", Descricao = "Outras deduções e exclusões de caráter geral", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "01;02;03;04;05;06", IndAjuste = "P", Grupo = "000", IndOutros = "S", IndTipoDeducoes = "G" },
				new Ref712() { Id = 8, Codigo = "D0101", Descricao = "Despesas incorridas nas operações de intermediação financeira", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "01;06", IndAjuste = "P", Grupo = "100", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 9, Codigo = "D0102", Descricao = "Encargos com obrigações por refinanciamentos, empréstimos e repasses de recursos de órgãos e instituições oficiais ou de direito privado", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "01;06", IndAjuste = "P", Grupo = "100", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 10, Codigo = "D0103", Descricao = "Despesas de câmbio", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "01;06", IndAjuste = "P", Grupo = "100", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 11, Codigo = "D0104", Descricao = "Despesas de arrendamento mercantil, restritas a empresas e instituições arrendadoras", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "01;06", IndAjuste = "P", Grupo = "100", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 12, Codigo = "D0105", Descricao = "Despesas de operações especiais por conta e ordem do Tesouro Nacional", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "01;06", IndAjuste = "P", Grupo = "100", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 13, Codigo = "D0106", Descricao = "Deságio na colocação de títulos", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "01;06", IndAjuste = "P", Grupo = "100", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 14, Codigo = "D0107", Descricao = "Perdas com títulos de renda fixa e variável, exceto com ações", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "01;06", IndAjuste = "P", Grupo = "100", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 15, Codigo = "D0108", Descricao = "Perdas com ativos financeiros e mercadorias, em operações de hedge", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "01;06", IndAjuste = "P", Grupo = "100", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 16, Codigo = "D0109", Descricao = "Despesas de captação em operações realizadas no mercado interfinanceiro, inclusive com títulos públicos", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "01;06", IndAjuste = "P", Grupo = "100", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 17, Codigo = "D0110", Descricao = "Valor auferido em cada período de apuração como remuneração pelos serviços de arrecadação de receitas federais, dividido por 0,04 (quatro centésimos). (dedução específica na base de cálculo da Cofis)", DataInicial = DateTime.ParseExact("01012014", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "01;06", IndAjuste = "P", Grupo = "100", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 18, Codigo = "D0190", Descricao = "Outras deduções e exclusões de caráter específico", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "01;06", IndAjuste = "P", Grupo = "100", IndOutros = "S", IndTipoDeducoes = "E" },
				new Ref712() { Id = 19, Codigo = "D0198", Descricao = "Ajustes Negativos das deduções e exclusões de caráter específico", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "01;06", IndAjuste = "N", Grupo = "100", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 20, Codigo = "D0199", Descricao = "Ajustes Positivos das deduções e exclusões de caráter específico", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "01;06", IndAjuste = "P", Grupo = "100", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 21, Codigo = "D0201", Descricao = "Cosseguro e resseguro cedidos", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = DateTime.ParseExact("31122013", "ddMMyyyy", CultureInfo.InvariantCulture), IndTipoAtividade = "02;06", IndAjuste = "P", Grupo = "200", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 22, Codigo = "D0201", Descricao = "Prêmios Cancelados e Restituídos", DataInicial = DateTime.ParseExact("01012014", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "02;06", IndAjuste = "P", Grupo = "200", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 23, Codigo = "D0202", Descricao = "Cancelamentos e restituições de prêmios que houverem sido computados como receitas", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = DateTime.ParseExact("31122013", "ddMMyyyy", CultureInfo.InvariantCulture), IndTipoAtividade = "02;06", IndAjuste = "P", Grupo = "200", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 24, Codigo = "D0202", Descricao = "Cancelamentos e Restituições de Cosseguro Aceito", DataInicial = DateTime.ParseExact("01012014", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "02;06", IndAjuste = "P", Grupo = "200", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 25, Codigo = "D0203", Descricao = "Parcela dos prêmios destinada à constituição de provisões ou reservas técnicas", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = DateTime.ParseExact("31122013", "ddMMyyyy", CultureInfo.InvariantCulture), IndTipoAtividade = "02;06", IndAjuste = "P", Grupo = "200", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 26, Codigo = "D0203", Descricao = "Cosseguro Cedido", DataInicial = DateTime.ParseExact("01012014", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "02;06", IndAjuste = "P", Grupo = "200", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 27, Codigo = "D0204", Descricao = "Parcela dos prêmios destinada à constituição de provisões ou reservas técnicasIndenizações correspondentes aos sinistros ocorridos, efetivamente pagos, deduzidos das importâncias recebidas a título de cosseguros e resseguros, salvados e outros ressarcimentos", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = DateTime.ParseExact("31122013", "ddMMyyyy", CultureInfo.InvariantCulture), IndTipoAtividade = "02;06", IndAjuste = "P", Grupo = "200", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 28, Codigo = "D0204", Descricao = "Parcela dos prêmios destinada à constituição de provisões ou reservas técnicas", DataInicial = DateTime.ParseExact("01012014", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "02;06", IndAjuste = "P", Grupo = "200", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 29, Codigo = "D0205", Descricao = "Indenizações correspondentes aos sinistros ocorridos, efetivamente pagos, deduzidos das importâncias recebidas a título de cosseguros e resseguros, salvados e outros ressarcimentos", DataInicial = DateTime.ParseExact("01012014", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "02;06", IndAjuste = "P", Grupo = "200", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 30, Codigo = "D0206", Descricao = "Prêmios de Resseguros", DataInicial = DateTime.ParseExact("01012014", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "02;06", IndAjuste = "P", Grupo = "200", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 31, Codigo = "D0207", Descricao = "Prêmios de Retrocessões Cedidas", DataInicial = DateTime.ParseExact("01012014", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "02;06", IndAjuste = "P", Grupo = "200", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 32, Codigo = "D0208", Descricao = "Cancelamento e/ou Restituições de Prêmios de Resseguro", DataInicial = DateTime.ParseExact("01012014", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "02;06", IndAjuste = "P", Grupo = "200", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 33, Codigo = "D0209", Descricao = "Variação das Provisões Técnicas de Retrocessão", DataInicial = DateTime.ParseExact("01012014", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "02;06", IndAjuste = "P", Grupo = "200", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 34, Codigo = "D0210", Descricao = "Indenizações (correspondentes aos sinistros ocorridos, efetivamente pagos)", DataInicial = DateTime.ParseExact("01012014", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "02;06", IndAjuste = "P", Grupo = "200", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 35, Codigo = "D0290", Descricao = "Outras deduções e exclusões de caráter específico", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "02;06", IndAjuste = "P", Grupo = "200", IndOutros = "S", IndTipoDeducoes = "E" },
				new Ref712() { Id = 36, Codigo = "D0298", Descricao = "Ajustes Negativos das deduções e exclusões de caráter específico", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "02;06", IndAjuste = "N", Grupo = "200", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 37, Codigo = "D0299", Descricao = "Ajustes Positivos das deduções e exclusões de caráter específico", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "02;06", IndAjuste = "P", Grupo = "200", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 38, Codigo = "D0301", Descricao = "Parcela das contribuições destinada à constituição de provisões ou reservas técnicas", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "03;06", IndAjuste = "P", Grupo = "300", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 39, Codigo = "D0302", Descricao = "Rendimentos auferidos nas aplicações financeiras de recursos destinados ao pagamento de benefícios de aposentadoria, pensão, pecúlio e de resgates", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = DateTime.ParseExact("31122013", "ddMMyyyy", CultureInfo.InvariantCulture), IndTipoAtividade = "03;06", IndAjuste = "P", Grupo = "300", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 40, Codigo = "D0302", Descricao = "Rendimentos auferidos nas aplicações financeiras destinadas ao pagamento de benefícios de aposentadoria, pensão, pecúlio e de resgates", DataInicial = DateTime.ParseExact("01012014", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "03;06", IndAjuste = "P", Grupo = "300", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 41, Codigo = "D0303", Descricao = "Rendimentos dos ativos financeiros garantidores das provisões técnicas de empresas de seguros privados destinadas exclusivamente a planos de benefícios de caráter previdenciário e a seguros de vida com cláusula de cobertura por sobrevivência", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "03;06", IndAjuste = "P", Grupo = "300", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 42, Codigo = "D0390", Descricao = "Outras deduções e exclusões de caráter específico", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "03;06", IndAjuste = "P", Grupo = "300", IndOutros = "S", IndTipoDeducoes = "E" },
				new Ref712() { Id = 43, Codigo = "D0398", Descricao = "Ajustes Negativos das deduções e exclusões de caráter específico", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "03;06", IndAjuste = "N", Grupo = "300", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 44, Codigo = "D0399", Descricao = "Ajustes Positivos das deduções e exclusões de caráter específico", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "03;06", IndAjuste = "P", Grupo = "300", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 45, Codigo = "D0401", Descricao = "Parcela dos prêmios destinada à constituição de provisões ou reservas técnicas", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "04;06", IndAjuste = "P", Grupo = "400", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 46, Codigo = "D0402", Descricao = "Rendimentos auferidos nas aplicações financeiras destinadas ao pagamento de resgate de títulos", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "04;06", IndAjuste = "P", Grupo = "400", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 47, Codigo = "D0490", Descricao = "Outras deduções e exclusões de caráter específico", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "04;06", IndAjuste = "P", Grupo = "400", IndOutros = "S", IndTipoDeducoes = "E" },
				new Ref712() { Id = 48, Codigo = "D0498", Descricao = "Ajustes Negativos das deduções e exclusões de caráter específico", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "04;06", IndAjuste = "N", Grupo = "400", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 49, Codigo = "D0499", Descricao = "Ajustes Positivos das deduções e exclusões de caráter específico", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "04;06", IndAjuste = "P", Grupo = "400", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 50, Codigo = "D0501", Descricao = "Rendimentos relativos a receitas de aluguel, destinados ao pagamento de benefícios de aposentadoria, pensão, pecúlio e resgates", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "03;06", IndAjuste = "P", Grupo = "500", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 51, Codigo = "D0502", Descricao = "Receita decorrente da venda de bens imóveis, destinada ao pagamento de benefícios de aposentadoria, pensão, pecúlio e resgates", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "03;06", IndAjuste = "P", Grupo = "500", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 52, Codigo = "D0503", Descricao = "Resultado positivo, auferido na reavaliação da carteira de investimentos imobiliários referida nos códigos 501 e 502", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "03;06", IndAjuste = "P", Grupo = "500", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 53, Codigo = "D0590", Descricao = "Outras deduções e exclusões de caráter específico", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "03;06", IndAjuste = "P", Grupo = "500", IndOutros = "S", IndTipoDeducoes = "E" },
				new Ref712() { Id = 54, Codigo = "D0598", Descricao = "Ajustes Negativos das deduções e exclusões de caráter específico", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "03;06", IndAjuste = "N", Grupo = "500", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 55, Codigo = "D0599", Descricao = "Ajustes Positivos das deduções e exclusões de caráter especifico", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "03;06", IndAjuste = "P", Grupo = "500", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 56, Codigo = "D0601", Descricao = "Co-responsabilidades cedidas", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "05;06", IndAjuste = "P", Grupo = "600", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 57, Codigo = "D0602", Descricao = "Parcela das contraprestações pecuniárias destinada à constituição de provisões técnicas", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "05;06", IndAjuste = "P", Grupo = "600", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 58, Codigo = "D0603", Descricao = "Valor referente às indenizações correspondentes aos eventos ocorridos, efetivamente pago, deduzido das importâncias recebidas a título de transferência de responsabilidades", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "05;06", IndAjuste = "P", Grupo = "600", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 59, Codigo = "D0690", Descricao = "Outras deduções e exclusões de caráter específico", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "05;06", IndAjuste = "P", Grupo = "600", IndOutros = "S", IndTipoDeducoes = "E" },
				new Ref712() { Id = 60, Codigo = "D0698", Descricao = "Ajustes Negativos das deduções e exclusões de caráter específico", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "05;06", IndAjuste = "N", Grupo = "600", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 61, Codigo = "D0699", Descricao = "Ajustes Positivos das deduções e exclusões de caráter específico", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "05;06", IndAjuste = "P", Grupo = "600", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 62, Codigo = "D0701", Descricao = "Despesas incorridas nas operações de intermediação financeira", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = DateTime.ParseExact("31012014", "ddMMyyyy", CultureInfo.InvariantCulture), IndTipoAtividade = "01;06", IndAjuste = "P", Grupo = "700", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 63, Codigo = "D0702", Descricao = "Encargos com obrigações por refinanciamentos, empréstimos e repasses de recursos de órgãos e instituições oficiais ou de direito privado", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = DateTime.ParseExact("31012014", "ddMMyyyy", CultureInfo.InvariantCulture), IndTipoAtividade = "01;06", IndAjuste = "P", Grupo = "700", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 64, Codigo = "D0703", Descricao = "Perdas com títulos de renda fixa e variável, exceto com ações", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = DateTime.ParseExact("31012014", "ddMMyyyy", CultureInfo.InvariantCulture), IndTipoAtividade = "01;06", IndAjuste = "P", Grupo = "700", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 65, Codigo = "D0704", Descricao = "Perdas com ativos financeiros e mercadorias em operações de hedge", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = DateTime.ParseExact("31012014", "ddMMyyyy", CultureInfo.InvariantCulture), IndTipoAtividade = "01;06", IndAjuste = "P", Grupo = "700", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 66, Codigo = "D0705", Descricao = "Ingressos decorrentes de ato cooperativo: Receitas de juros e encargos recebidas diretamente dos associados", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "01;06", IndAjuste = "P", Grupo = "700", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 67, Codigo = "D0706", Descricao = "Ingressos decorrentes de ato cooperativo: Receitas da prestação de serviços realizados aos associados e recebidas diretamente dos mesmos", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = DateTime.ParseExact("31012014", "ddMMyyyy", CultureInfo.InvariantCulture), IndTipoAtividade = "01;06", IndAjuste = "P", Grupo = "700", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 68, Codigo = "D0707", Descricao = "Ingressos decorrentes de ato cooperativo: Receitas financeiras recebidas de aplicações efetuadas em confederação, federação e cooperativa singular de que seja associada", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = DateTime.ParseExact("31012014", "ddMMyyyy", CultureInfo.InvariantCulture), IndTipoAtividade = "01;06", IndAjuste = "P", Grupo = "700", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 69, Codigo = "D0708", Descricao = "Ingressos decorrentes de ato cooperativo: Valores arrecadados com a venda de bens móveis e imóveis recebidos de associados para pagamento de empréstimo contraído junto à cooperativa", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = DateTime.ParseExact("31012014", "ddMMyyyy", CultureInfo.InvariantCulture), IndTipoAtividade = "01;06", IndAjuste = "P", Grupo = "700", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 70, Codigo = "D0709", Descricao = "Ingressos decorrentes de ato cooperativo: Valores recebidos de órgãos públicos ou de seguradoras para a liquidação parcial ou total de empréstimos contraídos por associados, em decorrência de perda de produção agropecuária, no caso de cooperativas de crédito rural", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = DateTime.ParseExact("31012014", "ddMMyyyy", CultureInfo.InvariantCulture), IndTipoAtividade = "01;06", IndAjuste = "P", Grupo = "700", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 71, Codigo = "D0710", Descricao = "Sobras líquidas apuradas na Demonstração do Resultado do Exercício, antes da destinação para a constituição do Fundo de Reserva e do Fundo de Assistência Técnica, Educacional e Social (Fates), previstos no art. 28 da Lei nº 5.764, de 1971.", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "01;06", IndAjuste = "P", Grupo = "700", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 72, Codigo = "D0790", Descricao = "Outras deduções e exclusões de caráter específico", DataInicial = DateTime.ParseExact("01012013", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "01;06", IndAjuste = "P", Grupo = "700", IndOutros = "S", IndTipoDeducoes = "E" },
				new Ref712() { Id = 73, Codigo = "D0798", Descricao = "Ajustes Negativos das deduções e exclusões de caráter específico", DataInicial = DateTime.ParseExact("01012014", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "01;06", IndAjuste = "N", Grupo = "700", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 74, Codigo = "D0799", Descricao = "Ajustes Positivos das deduções e exclusões de caráter específico", DataInicial = DateTime.ParseExact("01012014", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "01;06", IndAjuste = "P", Grupo = "700", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 75, Codigo = "D0801", Descricao = "Despesas de Captação de recursos para a Securitização de Créditos Imobiliários", DataInicial = DateTime.ParseExact("01012014", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "02;06", IndAjuste = "P", Grupo = "800", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 76, Codigo = "D0802", Descricao = "Despesas de Captação de recursos para a Securitização de Créditos Financeiros", DataInicial = DateTime.ParseExact("01012014", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "02;06", IndAjuste = "P", Grupo = "800", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 77, Codigo = "D0803", Descricao = "Despesas de Captação de recursos para a Securitização de Créditos Agrícolas", DataInicial = DateTime.ParseExact("01012014", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "02;06", IndAjuste = "P", Grupo = "800", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 78, Codigo = "D0898", Descricao = "Ajustes Negativos das deduções e exclusões de caráter específico", DataInicial = DateTime.ParseExact("01012014", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "02;06", IndAjuste = "N", Grupo = "800", IndOutros = "N", IndTipoDeducoes = "E" },
				new Ref712() { Id = 79, Codigo = "D0899", Descricao = "Ajustes Positivos das deduções e exclusões de caráter específico", DataInicial = DateTime.ParseExact("01012014", "ddMMyyyy", CultureInfo.InvariantCulture), DataFinal = null, IndTipoAtividade = "02;06", IndAjuste = "P", Grupo = "800", IndOutros = "N", IndTipoDeducoes = "E" }
			);
		}
    }
}
